DEFAULT_PERIODS = [
    {
        "title": "上午",
        "slots": [
            {"time": "09:00", "status": "rest", "capacity": 1},
            {"time": "10:00", "status": "available", "capacity": 1},
            {"time": "11:00", "status": "available", "capacity": 1},
        ],
    },
    {
        "title": "下午",
        "slots": [
            {"time": "13:00", "status": "available", "capacity": 1},
            {"time": "14:00", "status": "available", "capacity": 1},
            {"time": "15:00", "status": "available", "capacity": 1},
            {"time": "16:00", "status": "available", "capacity": 1},
            {"time": "17:00", "status": "available", "capacity": 1},
        ],
    },
    {
        "title": "晚上",
        "slots": [
            {"time": "19:00", "status": "rest", "capacity": 1},
            {"time": "20:00", "status": "rest", "capacity": 1},
        ],
    },
]


DEFAULT_MINIAPP_CONFIG = {
    "brand": "Benson",
    "shopName": "A hair salon(白土坝店)",
    "supportText": "抖音勇猛乐哥提供软件技术支持 当前版本0.01",
    "contactPhone": "13362325441",
    "banners": [
        {
            "id": 1,
            "type": "image",
            "title": "变美指南",
            "subtitle": "the Beauty Diary",
            "mediaUrl": "",
            "bgColor": "#d7c1ff",
            "enabled": True,
        },
        {
            "id": 2,
            "type": "video",
            "title": "专业造型",
            "subtitle": "Salon Studio",
            "mediaUrl": "",
            "bgColor": "#64c7ff",
            "enabled": True,
        },
        {
            "id": 3,
            "type": "image",
            "title": "焕新护理",
            "subtitle": "Hair Care Season",
            "mediaUrl": "",
            "bgColor": "#ffe071",
            "enabled": True,
        },
    ],
    "categories": [
        {"id": 1, "label": "面部专区", "icon": "面", "bgColor": "#c46ce7", "enabled": True},
        {"id": 2, "label": "美发护理", "icon": "剪", "bgColor": "#b95fd8", "enabled": True},
        {"id": 3, "label": "SPA专区", "icon": "SPA", "bgColor": "#ca78e7", "enabled": True},
        {"id": 4, "label": "新人专区", "icon": "新", "bgColor": "#bd61df", "enabled": True},
    ],
    "recommends": [
        {
            "id": 1,
            "imageUrl": "",
            "title": "【限首次】美白套餐-超皮秒嫩肤+M22光子嫩肤",
            "tag": "New",
            "label": "新人专区",
            "action": "新人活动",
            "price": 680,
            "buttonText": "预约",
            "bgColor": "#f8d7df",
            "enabled": True,
        },
        {
            "id": 2,
            "imageUrl": "",
            "title": "【限首次】头皮舒缓护理+发丝修护",
            "tag": "Hair Style",
            "label": "美发护理",
            "action": "美发护发",
            "price": 398,
            "buttonText": "预约",
            "bgColor": "#d7edf0",
            "enabled": True,
        },
        {
            "id": 3,
            "imageUrl": "",
            "title": "肩颈放松SPA+香氛头疗",
            "tag": "SPA",
            "label": "SPA专区",
            "action": "放松身心",
            "price": 298,
            "buttonText": "预约",
            "bgColor": "#d8ccff",
            "enabled": True,
        },
        {
            "id": 4,
            "imageUrl": "",
            "title": "法式层次剪裁+质感染发套餐",
            "tag": "Color",
            "label": "染烫专区",
            "action": "显白发色",
            "price": 520,
            "buttonText": "预约",
            "bgColor": "#ffd7a8",
            "enabled": True,
        },
    ],
    "stylist": {
        "title": "服务人员",
        "name": "Benson",
        "role": "你的专属发型师",
        "avatarBg": "#dbe7ff",
    },
    "dailySchedule": {
        "enabled": True,
        "periods": DEFAULT_PERIODS,
    },
    "restDays": [],
    "periods": DEFAULT_PERIODS,
    "holidayConfig": {
        "festivalDays": ["08-08", "08-22", "09-09", "09-21", "10-01", "10-02", "10-18"],
        "extraWorkdays": ["08-16", "09-06", "10-10"],
        "randomSeed": "hair-booking-demo",
    },
}
